modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"
logoFile = "${mod_icon}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
description = '''${mod_description}'''
authors = "${mod_author}"

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[43,50)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange="${version_range}"
ordering = "NONE"
side = "CLIENT"